export default {
    USER_LOGGEDIN: 'USER_LOGGEDIN',
    USER_LOGOUT: 'USER_LOGOUT',
    FETCH_CHARITIES: 'FETCH_CHARITIES',
    FETCH_CHARITY: 'FETCH_CHARITY',
    SET_CHARITY: 'SET_CHARITY',
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    FETCH_PRODUCT: 'FETCH_PRODUCT',
    SET_PRODUCT: 'SET_PRODUCT'
}